# Generated by Django 5.2 on 2025-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-26 17:05:00'),
            preserve_default=False,
        ),
    ]
