# Generated by Django 5.2 on 2025-05-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
