# Generated by Django 5.2 on 2025-04-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_roommember_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='base.category'),
            preserve_default=False,
        ),
    ]
